/**
 * ROLE_TEKV_ADMIN = 0
 * ROLE_ADMIN = 1
 * ROLE_USER = 2
 * ROLE_APP_EMAILCONFIGURATION = 3
 * ROLE_APP_BRANDING = 4
 * ROLE_APP_LICENSEMANAGEMENT = 5
 */
export enum Role {
    ROLE_TEKV_ADMIN = 0,
    ROLE_ADMIN,
    ROLE_USER,
    ROLE_APP_EMAILCONFIGURATION,
    ROLE_APP_BRANDING,
    ROLE_APP_LICENSEMANAGEMENT
}
