# Workflow to build and deploy to Azure cloud the License Server UI  

name: Nightly Build Daily Release


on:
  schedule:
    - cron: '*/5 * * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 12.20
      uses: actions/setup-node@v1
      with:
        node-version: '12.20'
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H_%M_%S')"

    - name: Build Angular Production web app
      run: |
        cd ./ui
        npm install
        npm run build:prod
    
    - name: Archive UI Production Build
      uses: vimtor/action-zip@v1
      with:
        files: './ui/dist/'
        recursive: true
        dest: 'prod-release-${{steps.date.outputs.date}}.zip'
    
    - name: Build Angular Integration web app
      run: |
        cd ./ui
        npm install
        npm run build
    
    - name: Archive UI Integration Build
      uses: vimtor/action-zip@v1
      with:
        files: './ui/dist/'
        recursive: true
        dest: 'integration-release-${{steps.date.outputs.date}}.zip'

    - name: Archive Full Build
      uses: vimtor/action-zip@v1
      with:
        files: 'integration-release-${{steps.date.outputs.date}}.zip prod-release-${{steps.date.outputs.date}}.zip'
        recursive: true        
        dest: 'LS-release-${{steps.date.outputs.date}}.zip'
    
    - name: Upload Build
      uses: su-dont/share-point-uploader@v2.1
      with:
        sp_url: ${{ secrets.SP_URL }}
        sp_username: ${{ secrets.USERNAME }}
        sp_password: ${{ secrets.PASSWORD }}
        sp_folder: ${{ secrets.SP_FOLDER }}
        sp_file_name: 'LS-release-${{steps.date.outputs.date}}.zip'
        file: 'LS-release-${{steps.date.outputs.date}}.zip'

        