name: License Server CI/CD

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # - name: Run API tests
    #   uses: matt-ball/newman-action@master
    #   with:
    #     collection: ./tests/LicenseServerAPIs.postman_collection.json
    #     environment: ./tests/LicenseServerAPIsEnv.postman_environment.json
         
    - name: Run API Tests
      id: run-newman
      uses: anthonyvscode/newman-action@v1
      with:
        collection: ./tests/LicenseServerAPIs.postman_collection.json
        environment: ./tests/LicenseServerAPIsEnv.postman_environment.json
        reporters: cli

    - name: Output summary to console
      run: echo ${{ steps.run-newman.outputs.summary }}