name: License Server CI/CD

on:
  workflow_dispatch:
  push:
    branches: [master]

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Commit Short Hash
        id: hash
        run: echo "hash=$(git rev-parse --short "$RELEVANT_SHA")" >> $GITHUB_OUTPUT
        env:
          RELEVANT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Print Relevant SHA
        run: |
          echo "${{steps.hash.outputs.hash}}"
