name: License Server CI/CD

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run API tests
      id: run-newman
      uses: matt-ball/newman-action@master
      with:
        collection: ./tests/LicenseServerAPIs.postman_collection.json
        environment: ./tests/LicenseServerAPIsEnv.postman_environment.json
        reporters: '["junit"]'
        # reporter: "{ \"junit\": { \"export\": \"./tests/newman-report.xml\" }"
    
    - name: showdetails
      run: |
        pwd
        cd tests
        ls

    - name: Publish JUnit Report
      uses: mikepenz/action-junit-report@v3
      if: always() # always run even if the previous step fails
      with:
        report_paths: './tests/newman-report.xml'
        summary: 'true'