name: License Server CI/CD

on:
  push:
    branches: [ master ]
    
permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Get Latest tag
      id: current_tag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
    
    - name: 'Get next minor version'
      id: next_tag
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.current_tag.outputs.tag }}
      
    - name: Replace Build Version
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "[build_version]"
        replace: "${{ steps.next_tag.outputs.patch }}"
        include: "./ui/src/app/generics/about-modal/**"
        regex: false
    
    - name: Print File
      run: cat ./ui/src/app/generics/about-modal/about-modal.component.html