# Workflow to build and deploy to Azure cloud the License Server UI  

name: Pull Request Action

# Controls when the workflow will run
on:
  [pull_request]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Use Node.js 12.20
      uses: actions/setup-node@v1
      with:
        node-version: '12.20'
    
    # - name: Angular Test web app
    #   run: |
    #     cd ./ui
    #     npm install
    #     npm run test -- --no-watch --no-progress

    # - name: Publish Test Results
    #   uses: EnricoMi/publish-unit-test-result-action@v1
    #   if: always()
    #   with:
    #     files: "ui/test-results/*.xml"
  
    # - name: Comment Test Coverage
    #   uses: AthleticNet/comment-test-coverage@1.1
    #   if: always()
    #   with:
    #     token: ${{ github.token }}
    #     path: ui/test-results/coverage-summary.json
    #     title: Karma Test Coverage
