# Workflow to build and deploy to Azure cloud the License Server UI  

name: Push Release

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Version'
        required: true
        default: 'latest'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Install Zip
          uses: montudor/action-zip@v1

        - name: Retrieve release assets
          uses: dsaltares/fetch-gh-release-asset@master
          with:
            version: '${{ github.event.inputs.release_version }}'
            regex: true
            file: "LS"
            target: "./"
        
        - name: Unzip Release Folder
          run: unzip -qq *.zip -d Release
        
        - name: Check if file is present
          run: |
            cd Release
            ls
        
        - name: Unzip Integration UI
          run: unzip -qq integration*.zip -d Integration-build
          working-directory: Release

        - name: Check if file is present
          run: |
            cd Release
            ls